// dummyData.js
const ProductData = [
   {
    id: '1',
    title: 'Luxury Hair Kit',
    price: 1499,
    oldPrice: 1799,
    discount: Math.round(((1799 - 1499) / 1799) * 100), // Auto calculate %
    image: require('../assets/newPic.png'),
    rating: 4,
    review: 48,
    description: 'Complete hair nourishment in one kit',
    offer: '🔖 Save ₹300 on combo purchase',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    itemsList: [
      '✅ Shampoo (250ml)',
      '✅ Conditioner (250ml)',
      '✅ Hair Mask (200g)',
      '✅ Hair Serum (50ml)',
    ],
    usage: [
      '- Use shampoo & conditioner twice weekly',
      '- Apply hair mask once a week',
      '- Serum for daily hair protection',
    ],
    tag: 'Repair & shine',
  },
  {
    id: '2',
    title: 'Beard Care Pro',
    price: 499,
    oldPrice: 699,
    discount: Math.round(((699 - 499) / 699) * 100),
    image: require('../assets/newPic.png'),
    rating: 4,
    review: 30,
    description: 'Shape & nourish beard with pro care',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    offer: '✨ Flat ₹200 off',
    itemsList: [
      '✅ Beard Oil (50ml)',
      '✅ Beard Balm (30g)',
      '✅ Wooden Comb',
    ],
    usage: [
      '- Apply oil daily for nourishment',
      '- Use balm for styling',
      '- Comb beard twice a day',
    ],
    tag: 'Ideal for oily skin',
  },
  {
    id: '3',
    title: 'Glow & Go Pack',
    price: 599,
    oldPrice: 899,
    discount: Math.round(((899 - 599) / 899) * 100),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    image: require('../assets/newPic.png'),
    rating: 5,
    review: 75,
    description: 'Quick glow for your party look',
    offer: '🔥 Save ₹300 instantly',
    itemsList: [
      '✅ Facewash',
      '✅ Bleach Cream',
      '✅ Threading Kit',
    ],
    usage: [
      '- Wash face daily',
      '- Use bleach cream once a week',
      '- Threading as required',
    ],
    tag: 'Quick glow for party',
  },
   {
    id: '4',
    title: 'Luxury Hair Kit',
    price: 1499,
    oldPrice: 1799,
    discount: Math.round(((1799 - 1499) / 1799) * 100), // Auto calculate %
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 4,
    review: 48,
    description: 'Complete hair nourishment in one kit',
    offer: '🔖 Save ₹300 on combo purchase',
    itemsList: [
      '✅ Shampoo (250ml)',
      '✅ Conditioner (250ml)',
      '✅ Hair Mask (200g)',
      '✅ Hair Serum (50ml)',
    ],
    usage: [
      '- Use shampoo & conditioner twice weekly',
      '- Apply hair mask once a week',
      '- Serum for daily hair protection',
    ],
    tag: 'Shape & nourish',
  },
  {
    id: '5',
    title: 'Beard Care Pro',
    price: 499,
    oldPrice: 699,
    discount: Math.round(((699 - 499) / 699) * 100),
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 4,
    review: 30,
    description: 'Shape & nourish beard with pro care',
    offer: '✨ Flat ₹200 off',
    itemsList: [
      '✅ Beard Oil (50ml)',
      '✅ Beard Balm (30g)',
      '✅ Wooden Comb',
    ],
    usage: [
      '- Apply oil daily for nourishment',
      '- Use balm for styling',
      '- Comb beard twice a day',
    ],
    tag: 'Repair & shine',
  },
  {
    id: '6',
    title: 'Glow & Go Pack',
    price: 599,
    oldPrice: 899,
    discount: Math.round(((899 - 599) / 899) * 100),
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 5,
    review: 75,
    description: 'Quick glow for your party look',
    offer: '🔥 Save ₹300 instantly',
    itemsList: [
      '✅ Facewash',
      '✅ Bleach Cream',
      '✅ Threading Kit',
    ],
    usage: [
      '- Wash face daily',
      '- Use bleach cream once a week',
      '- Threading as required',
    ],
     tag: 'Quick glow for party',
  },
   {
    id: '7',
    title: 'Luxury Hair Kit',
    price: 1499,
    oldPrice: 1799,
    discount: Math.round(((1799 - 1499) / 1799) * 100), // Auto calculate %
    image: require('../assets/newPic.png'),
    rating: 4,
    review: 48,
    description: 'Complete hair nourishment in one kit',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    offer: '🔖 Save ₹300 on combo purchase',
    itemsList: [
      '✅ Shampoo (250ml)',
      '✅ Conditioner (250ml)',
      '✅ Hair Mask (200g)',
      '✅ Hair Serum (50ml)',
    ],
    usage: [
      '- Use shampoo & conditioner twice weekly',
      '- Apply hair mask once a week',
      '- Serum for daily hair protection',
    ],
     tag: 'Repair & nourish',
  },
  {
    id: '8',
    title: 'Beard Care Pro',
    price: 499,
    oldPrice: 699,
    discount: Math.round(((699 - 499) / 699) * 100),
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 4,
    review: 30,
    description: 'Shape & nourish beard with pro care',
    offer: '✨ Flat ₹200 off',
    itemsList: [
      '✅ Beard Oil (50ml)',
      '✅ Beard Balm (30g)',
      '✅ Wooden Comb',
    ],
    usage: [
      '- Apply oil daily for nourishment',
      '- Use balm for styling',
      '- Comb beard twice a day',
    ],
     tag: 'Shape & nourish',
  },
  {
    id: '9',
    title: 'Glow & Go Pack',
    price: 599,
    oldPrice: 899,
    discount: Math.round(((899 - 599) / 899) * 100),
    image: require('../assets/newPic.png'),
    rating: 5,
    review: 75,
    description: 'Quick glow for your party look',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    offer: '🔥 Save ₹300 instantly',
    itemsList: [
      '✅ Facewash',
      '✅ Bleach Cream',
      '✅ Threading Kit',
    ],
    usage: [
      '- Wash face daily',
      '- Use bleach cream once a week',
      '- Threading as required',
    ],
     tag: 'Quick glow for party',
  },
   {
    id: '10',
    title: 'Luxury Hair Kit',
    price: 1499,
    oldPrice: 1799,
    discount: Math.round(((1799 - 1499) / 1799) * 100), // Auto calculate %
    image: require('../assets/newPic.png'),
    rating: 4,
    review: 48,
    description: 'Complete hair nourishment in one kit',
    offer: '🔖 Save ₹300 on combo purchase',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    itemsList: [
      '✅ Shampoo (250ml)',
      '✅ Conditioner (250ml)',
      '✅ Hair Mask (200g)',
      '✅ Hair Serum (50ml)',
    ],
    usage: [
      '- Use shampoo & conditioner twice weekly',
      '- Apply hair mask once a week',
      '- Serum for daily hair protection',
    ],
    tag: 'Repair & shine',
  },
  {
    id: '11',
    title: 'Beard Care Pro',
    price: 499,
    oldPrice: 699,
    discount: Math.round(((699 - 499) / 699) * 100),
    image: require('../assets/newPic.png'),
    rating: 4,
    review: 30,
    description: 'Shape & nourish beard with pro care',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    offer: '✨ Flat ₹200 off',
    itemsList: [
      '✅ Beard Oil (50ml)',
      '✅ Beard Balm (30g)',
      '✅ Wooden Comb',
    ],
    usage: [
      '- Apply oil daily for nourishment',
      '- Use balm for styling',
      '- Comb beard twice a day',
    ],
    tag: 'Ideal for oily skin',
  },
  {
    id: '12',
    title: 'Glow & Go Pack',
    price: 599,
    oldPrice: 899,
    discount: Math.round(((899 - 599) / 899) * 100),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    image: require('../assets/newPic.png'),
    rating: 5,
    review: 75,
    description: 'Quick glow for your party look',
    offer: '🔥 Save ₹300 instantly',
    itemsList: [
      '✅ Facewash',
      '✅ Bleach Cream',
      '✅ Threading Kit',
    ],
    usage: [
      '- Wash face daily',
      '- Use bleach cream once a week',
      '- Threading as required',
    ],
    tag: 'Quick glow for party',
  },
   {
    id: '13',
    title: 'Luxury Hair Kit',
    price: 1499,
    oldPrice: 1799,
    discount: Math.round(((1799 - 1499) / 1799) * 100), // Auto calculate %
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 4,
    review: 48,
    description: 'Complete hair nourishment in one kit',
    offer: '🔖 Save ₹300 on combo purchase',
    itemsList: [
      '✅ Shampoo (250ml)',
      '✅ Conditioner (250ml)',
      '✅ Hair Mask (200g)',
      '✅ Hair Serum (50ml)',
    ],
    usage: [
      '- Use shampoo & conditioner twice weekly',
      '- Apply hair mask once a week',
      '- Serum for daily hair protection',
    ],
    tag: 'Shape & nourish',
  },
  {
    id: '14',
    title: 'Beard Care Pro',
    price: 499,
    oldPrice: 699,
    discount: Math.round(((699 - 499) / 699) * 100),
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 4,
    review: 30,
    description: 'Shape & nourish beard with pro care',
    offer: '✨ Flat ₹200 off',
    itemsList: [
      '✅ Beard Oil (50ml)',
      '✅ Beard Balm (30g)',
      '✅ Wooden Comb',
    ],
    usage: [
      '- Apply oil daily for nourishment',
      '- Use balm for styling',
      '- Comb beard twice a day',
    ],
    tag: 'Repair & shine',
  },
  {
    id: '15',
    title: 'Glow & Go Pack',
    price: 599,
    oldPrice: 899,
    discount: Math.round(((899 - 599) / 899) * 100),
    image: require('../assets/newPic.png'),
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    rating: 5,
    review: 75,
    description: 'Quick glow for your party look',
    offer: '🔥 Save ₹300 instantly',
    itemsList: [
      '✅ Facewash',
      '✅ Bleach Cream',
      '✅ Threading Kit',
    ],
    usage: [
      '- Wash face daily',
      '- Use bleach cream once a week',
      '- Threading as required',
    ],
     tag: 'Quick glow for party',
  },
   {
    id: '16',
    title: 'Glow & Go Pack',
    price: 599,
    oldPrice: 899,
    discount: Math.round(((899 - 599) / 899) * 100),
    image: require('../assets/newPic.png'),
    rating: 5,
    review: 75,
    description: 'Quick glow for your party look',
    line1: ['Bleach, Threading', 'Hair Cutting & Hair Coloring'],
    offer: '🔥 Save ₹300 instantly',
    itemsList: [
      '✅ Facewash',
      '✅ Bleach Cream',
      '✅ Threading Kit',
    ],
    usage: [
      '- Wash face daily',
      '- Use bleach cream once a week',
      '- Threading as required',
    ],
     tag: 'Quick glow for party',
  },
];

export default ProductData;